### ISSUE TITLE
Failed to grant gov module to create my validator

### ISSUE THREAD

**Issue by bq1024** [bnb-chain/greenfield#173]
I got this error when granting gov module to create my validator

```
$ gnfd tx authz grant 0x7b5Fe22B5446f7C62Ea27B8BD71CeF94e03f3dF2 delegate --spend-limit 1000000000000000000000BNB --allowed-validators ${VALIDATOR_ADDR} --from ${VALIDATOR_ADDR} --keyring-backend test --node "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443" --yes
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account 0x3Fe5Bd46A7EC803e51bdEbe8dB0063f4f6a63ca8 not found: key not found

$ gnfd version
Version: v0.1.1-1-g2a15a10
Git Commit: 2a15a10f2ff6984449f2bc90bf07a76e70551499
Git Commit Date: 20230410
Architecture: amd64
Go Version: go1.19.6
```

**Comment by isaacyuno** [comment]
You need to transfer some bnb to 0x3Fe5Bd46A7EC803e51bdEbe8dB0063f4f6a63ca8 first to create this account on Greenfield chain

**Comment by flyhxg** [comment]
> You need to transfer some bnb to 0x3Fe5Bd46A7EC803e51bdEbe8dB0063f4f6a63ca8 first to create this account on Greenfield chain

![1682237367392](https://user-images.githubusercontent.com/11693167/233827969-cb0856f3-0d24-4028-b54a-27dfd80f3705.png)

What is the reason for the failure after authorization?
