### ISSUE TITLE
failed to print unsigned std tx: post failed: Post "http://localhost:26657"

### ISSUE THREAD

**Issue by 0xxfu** [bnb-chain/greenfield#181]
1. follow the Setup Local Chain: https://github.com/bnb-chain/greenfield/tree/master/deployment
2. run step 1~4 completed
3. run step 5 raise an error:  Error: failed to print unsigned std tx: post failed: Post "http://localhost:26657": dial tcp 127.0.0.1:26657: connect: connection refused

`./build/bin/gnfd gentx validator 10000000000000000000000000BNB $VALIDATOR $RELAYER $CHALLENGER $BLS --keyring-backend=test --chain-id=greenfield_9000-121 \
    --moniker="validator" \
    --commission-max-change-rate=0.01 \
    --commission-max-rate=1.0 \
    --commission-rate=0.07`
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/11550519/232668604-2cf12120-fd8b-4cd6-b78b-132c256012d3.png">

**Comment by kris-ss** [comment]
Hello, we are checking this with the team. Will get back to you once we have updates.

**Comment by kris-ss** [comment]
Hi @0xxfu There was a typo on the guide. Please try the steps again here - https://github.com/bnb-chain/greenfield/tree/develop/deployment

**Comment by 0xxfu** [comment]
> Hi @0xxfu There was a typo on the guide. Please try the steps again here - https://github.com/bnb-chain/greenfield/tree/develop/deployment

Thanks. it work well now.
