### ISSUE TITLE
Authorization signature verification failed; 

### ISSUE THREAD

**Issue by flyhxg** [bnb-chain/greenfield#204]
![1682301248325](https://user-images.githubusercontent.com/11693167/233882052-71a5a829-e319-43a1-93bf-3874d2ed7c56.png)
May I ask what error this is?

**Comment by isaacyuno** [comment]
Which gnfd version are you using?

**Comment by flyhxg** [comment]
![image](https://user-images.githubusercontent.com/11693167/233897042-57f0a568-c4e1-474f-a48a-9a20c9027b22.png)

**Comment by flyhxg** [comment]
I switched to another version, but it doesn't work either
![1682310501104](https://user-images.githubusercontent.com/11693167/233900136-0cea028f-d267-4ebd-b335-47d8562797fe.png)
