### ISSUE TITLE
Can users grant permission to others to write objects to a bucket?

### ISSUE THREAD

**Issue by stopWarByWar** [bnb-chain/greenfield#228]
In the test for greenfield-go-sdk, specifically [test-example](https://github.com/bnb-chain/greenfield-go-sdk/blob/79ea3f5b0a816fe6b162a6dd860d71c96710ac5e/e2e/e2e_storage_test.go#L93), ACTION_CREATE_OBJECT is granted during PutBucketPolicy. However, according to greenfield-cmd, the bucket policy actions can be "update" or "delete". I am unsure which one is correct. Also, I would like to know if users can grant permission to others to write objects to a bucket.

**Comment by Fynnss** [comment]
Yes, users can grant CreateObject permission to others to allow them create object on its bucket.

If you are not sure which one is correct, please refer to go-sdk.
