### ISSUE TITLE
Whether the owner of the bucket can authorize others to write objects to the bucket

### ISSUE THREAD

**Issue by stopWarByWar** [bnb-chain/greenfield#289]
Whether the owner of the bucket can authorize others to write objects to the bucket. And how can i do it using go-sdk.

**Comment by deepcrazy** [comment]
Hi there, I believe this is possible. However, let me know check this with team about doing it using `go-sdk`.

Meanwhile, I believe it can be done using `group example`: https://github.com/bnb-chain/greenfield-go-sdk/blob/master/examples/group.go and `storage example`: https://github.com/bnb-chain/greenfield-go-sdk/blob/master/examples/storage.go

**Comment by KeefeL** [comment]
It is an operation about permission, take a look at this example: https://github.com/bnb-chain/greenfield/blob/master/e2e/tests/permission_test.go#L197
