### ISSUE TITLE
proof length is invalid 0: validator bls proof is invalid

### ISSUE THREAD

**Issue by Elhorses** [bnb-chain/greenfield#355]
1) exec condition:
MacOS M1
testnet_config.zip from https://github.com/bnb-chain/greenfield/releases/tag/v0.2.3-alpha.5

2) gnfd version:

Version: v0.2.3-alpha.5
Git Commit: d3bebb2f4d64f9780cb136169d4aaea51f6c973f
Git Commit Date: 20230713
Architecture: arm64
Go Version: go1.19.4
Operating System: darwin%     

3) run:  

./gnfd start --home ~/company_project/.gnfd

4) happened:

2:09PM INF starting node with ABCI Tendermint in-process module=server
2:09PM INF service start impl=multiAppConn module=proxy msg={}
2:09PM INF service start connection=query impl=localClient module=abci-client msg={}
2:09PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
2:09PM INF service start connection=mempool impl=localClient module=abci-client msg={}
2:09PM INF service start connection=consensus impl=localClient module=abci-client msg={}
2:09PM INF service start connection=eth_query impl=localClient module=abci-client msg={}
2:09PM INF service start connection=prefetch impl=localClient module=abci-client msg={}
2:09PM INF service start impl=EventBus module=events msg={}
2:09PM INF service start impl=PubSub module=pubsub msg={}
2:09PM INF service start impl=IndexerService module=txindex msg={}
2:09PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v0.2.3-alpha.5
2:09PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
2:09PM INF InitChain chainID=greenfield_5600-1 initialHeight=1 module=server
2:09PM INF initializing blockchain state from genesis.json module=server
panic: failed to execute DeliverTx for '{
          "body": {
            "messages": [
              {
                "@type": "/cosmos.staking.v1beta1.MsgCreateValidator",
                "description": {
                  "moniker": "Alpha-5",
                  "identity": "",
                  "website": "",
                  "security_contact": "",
                  "details": "Alpha-5"
                },
                "commission": {
                  "rate": "0.000000000000000000",
                  "max_rate": "1.000000000000000000",
                  "max_change_rate": "0.010000000000000000"
                },
                "min_self_delegation": "1000000000000000000000",
                "delegator_address": "0xd232339d21D20673CAb8c7EA2b7e96B1Ceb702C5",
                "validator_address": "0xd232339d21D20673CAb8c7EA2b7e96B1Ceb702C5",
                "pubkey": {
                  "@type": "/cosmos.crypto.ed25519.PubKey",
                  "key": "h3HfJh6R8nAMKVw1Lmp19B0qSZhnthqyErmLG0gm1nI="
                },
                "value": {
                  "denom": "BNB",
                  "amount": "1000000000000000000000"
                },
                "from": "0xd232339d21D20673CAb8c7EA2b7e96B1Ceb702C5",
                "relayer_address": "0x2283a68aa25e372eAdfE76adF604388C7b8EE10d",
                "challenger_address": "0x65460A347cD5244350B46343D3F961f0fC3B3Bfa",
                "bls_key": "b7130fb95ceb93c201e504bf5de99f7e2ccec983d6a59d5a2600a62dd87f89baf404ebaf60cdda9f7d28651819dd4c8f"
              }
            ],
            "memo": "Alpha-5@127.0.0.1:26656",
            "timeout_height": "0",
            "extension_options": [],
            "non_critical_extension_options": []
          },
          "auth_info": {
            "signer_infos": [
              {
                "public_key": {
                  "@type": "/cosmos.crypto.eth.ethsecp256k1.PubKey",
                  "key": "A5obp2TBEg3VjAJ0E386eR8l5vhhH4LTl6eyDV/yjwUP"
                },
                "mode_info": {
                  "single": {
                    "mode": "SIGN_MODE_EIP_712"
                  }
                },
                "sequence": "0"
              }
            ],
            "fee": {
              "amount": [],
              "gas_limit": "200000000",
              "payer": "",
              "granter": ""
            },
            "tip": null
          },
          "signatures": [
            "xNERDpPkdQoz2G4aF6KbaATjg6xOjyNJzhLRVEmVvbtsCbC5+zrtCXkeRQQ5JqYK02ZO6izARPSa7LFnvN5ImgA="
          ]
        }': proof length is invalid 0: validator bls proof is invalid

goroutine 14 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{_}, {_, _}, {_, _}, _, {_, _}}, {{0x106bcdb68, 0x140002f0230}, ...}, ...)
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.3-alpha.3/x/genutil/module.go:115 +0x118
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x106bcdb68, 0x140002f0230}, {0x106bdff40, 0x140006a75c0}, {{0x0, 0x0}, {0x14002348048, 0x11}, 0x0, ...}, ...}, ...)
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.3-alpha.3/types/module/module.go:357 +0x348
github.com/bnb-chain/greenfield/app.(*App).InitChainer(_, {{0x106bcdb68, 0x140002f0230}, {0x106bdff40, 0x140006a75c0}, {{0x0, 0x0}, {0x14002348048, 0x11}, 0x0, ...}, ...}, ...)
        /Users/fqw/company_project/greenfield/app/app.go:780 +0x514
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0x140013b4480, {{0x2d71aea8, 0xedc29a080, 0x0}, {0x14002348048, 0x11}, 0x14000f4f640, {0x107db55d8, 0x0, 0x0}, ...})
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.3-alpha.3/baseapp/abci.go:93 +0x470
github.com/cometbft/cometbft/abci/client.(*localClient).InitChainSync(0x140023b7260, {{0x2d71aea8, 0xedc29a080, 0x0}, {0x14002348048, 0x11}, 0x14000f4f640, {0x107db55d8, 0x0, 0x0}, ...})
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cometbft@v0.0.2-alpha.1/abci/client/local_client.go:265 +0x18c
github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChainSync(0x14002343ce0, {{0x2d71aea8, 0xedc29a080, 0x0}, {0x14002348048, 0x11}, 0x14000f4f640, {0x107db55d8, 0x0, 0x0}, ...})
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cometbft@v0.0.2-alpha.1/proxy/app_conn.go:97 +0x170
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x10592bc65, 0x6}}, {0x14002348048, 0x11}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cometbft@v0.0.2-alpha.1/consensus/replay.go:319 +0xae8
github.com/cometbft/cometbft/consensus.(*Handshaker).Handshake(0x1400145bc18, {0x106bea358, 0x14001516000})
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cometbft@v0.0.2-alpha.1/consensus/replay.go:268 +0x38c
github.com/cometbft/cometbft/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x10592bc65, 0x6}}, {0x14002348048, 0x11}, 0x1, 0x0, ...}, ...)
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cometbft@v0.0.2-alpha.1/node/node.go:344 +0x104
github.com/cometbft/cometbft/node.NewNode(0x140001789a0, {0x106bcdee8, 0x14002293720}, 0x1400231b860, {0x106bac0e0, 0x140023426c0}, 0x140013ff890?, 0x1?, 0x1400238ea30, {0x106bceea8, ...}, ...)
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cometbft@v0.0.2-alpha.1/node/node.go:821 +0x3f0
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x106be1600, 0x14001211860}, 0x0, {0x14000488708, 0x11}, {0x106beac80, ...}, ...}, ...)
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.3-alpha.3/server/start.go:365 +0x6f4
github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.3-alpha.3/server/start.go:162 +0x48
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.3-alpha.3/server/start.go:602 +0x30
created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile
        /Users/fqw/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.3-alpha.3/server/start.go:601 +0x1e4

**Comment by 0xLyon** [comment]
Hi there, thanks for the details shared. For now please use the previous release [v0.2.2-hf.3](https://github.com/bnb-chain/greenfield/releases/tag/v0.2.2-hf.3), as version 0.2.3 is a pre-release alpha version and should not be made use of just yet.
Please let me know if you experience the same issues on the mentioned version to use.
