### ISSUE TITLE
Encode events in transactions  into greenfield/proto/greenfield events

### ISSUE THREAD

**Issue by stopWarByWar** [bnb-chain/greenfield#513]
# Rationale
When developers handle the events from transactions, there isn't such a function that can decode the event in transactions into greenfield/proto/greenfield event. Therefore developers should write related decoding function for greenfield/proto/greenfield event one by one. This is very inconvenient。 

I think if there is such functions would be great.

**Comment by CocoStarZ** [comment]
What kinda events do you refer to? could you provide an example?
