### ISSUE TITLE
MODULE_NOT_FOUND for @bnb-chain/greenfiled-file-handle using pnpm

### ISSUE THREAD

**Issue by devhimanshuhc** [bnb-chain/greenfield#531]
#### System information

OS & Version: Windows 11

#### Expected behaviour
trying to run the nodejs storage.js  to create a bucket in the dceller.

I tried to use `pnpm install` but the issue still coming. I have installed pnpm in my system. even tried to install the particular package, i.e. `@bnb-chain/greenfiled-file-handle`

#### Actual behaviour
throwing this error=>
```
node:internal/modules/cjs/loader:573
      throw e;
      ^

Error: Cannot find module 'C:\Users\Himanshu Chauhan\OneDrive\Desktop\work\greenfield-js-sdk\examples\nodejs\node_modules\@bnb-chain\greenfiled-file-handle\dist\node\index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
    at resolveExports (node:internal/modules/cjs/loader:567:14)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\Himanshu Chauhan\OneDrive\Desktop\work\greenfield-js-sdk\examples\nodejs\storage.js:4:26)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Himanshu Chauhan\\OneDrive\\Desktop\\work\\greenfield-js-sdk\\examples\\nodejs\\node_modules\\@bnb-chain\\greenfiled-file-handle\\package.json'        
}
```

**Comment by STdevK** [comment]
can you share the contents of storage.js?

**Comment by devhimanshuhc** [comment]
> can you share the contents of storage.js?

haven't changed a single thing
```
const fs = require('fs');
const path = require('path');
const mimeTypes = require('mime-types');
const { getCheckSums } = require('@bnb-chain/greenfiled-file-handle');
const { client, selectSp, generateString } = require('./client');
const { ACCOUNT_ADDRESS, ACCOUNT_PRIVATEKEY } = require('./env');

const filePath = './CHANGELOG.md';
const bucketName = generateString(10);
const objectName = generateString(10);
const fileBuffer = fs.readFileSync(filePath);
const extname = path.extname(filePath);
const fileType = mimeTypes.lookup(extname);

(async () => {
  const spInfo = await selectSp();

  // create bucket example:
  const createBucketTx = await client.bucket.createBucket(
    {
      bucketName: bucketName,
      creator: ACCOUNT_ADDRESS,
      visibility: 'VISIBILITY_TYPE_PUBLIC_READ',
      chargedReadQuota: '0',
      spInfo: {
        primarySpAddress: spInfo.primarySpAddress,
      },
      paymentAddress: ACCOUNT_ADDRESS,
    },
    {
      type: 'ECDSA',
      privateKey: ACCOUNT_PRIVATEKEY,
    },
  );

  const createBucketTxSimulateInfo = await createBucketTx.simulate({
    denom: 'BNB',
  });

  console.log('createBucketTxSimulateInfo', createBucketTxSimulateInfo);

  const createBucketTxRes = await createBucketTx.broadcast({
    denom: 'BNB',
    gasLimit: Number(createBucketTxSimulateInfo?.gasLimit),
    gasPrice: createBucketTxSimulateInfo?.gasPrice || '5000000000',
    payer: ACCOUNT_ADDRESS,
    granter: '',
    privateKey: ACCOUNT_PRIVATEKEY,
  });

  console.log('create bucket success', createBucketTxRes);

  // create object example:
  const hashResult = await getCheckSums(fileBuffer);
  const { contentLength, expectCheckSums } = hashResult;

  const createObjectTx = await client.object.createObject(
    {
      bucketName: bucketName,
      objectName: objectName,
      creator: ACCOUNT_ADDRESS,
      visibility: 'VISIBILITY_TYPE_PRIVATE',
      fileType: fileType,
      redundancyType: 'REDUNDANCY_EC_TYPE',
      contentLength,
      expectCheckSums: JSON.parse(expectCheckSums),
    },
    {
      type: 'ECDSA',
      privateKey: ACCOUNT_PRIVATEKEY,
    },
  );

  const createObjectTxSimulateInfo = await createObjectTx.simulate({
    denom: 'BNB',
  });

  const createObjectTxRes = await createObjectTx.broadcast({
    denom: 'BNB',
    gasLimit: Number(createObjectTxSimulateInfo?.gasLimit),
    gasPrice: createObjectTxSimulateInfo?.gasPrice || '5000000000',
    payer: ACCOUNT_ADDRESS,
    granter: '',
    privateKey: ACCOUNT_PRIVATEKEY,
  });

  console.log('create object success', createObjectTxRes);
})();
```

**Comment by rrr523** [comment]
@devhimanshuhc 

what happened when `pnpm run -F "./packages/**"  -r build --force` is executed?

**Comment by rrr523** [comment]
@devhimanshuhc 

I guess that you executed `pnpm run -F "./packages/**"  -r build --force` in the `example/nodejs` directory. This may be inconsistent with the documentation.

Try this compile command: `pnpm -F "@bnb-chain/**" build`.

**Comment by devhimanshuhc** [comment]
> what happened when `pnpm run -F "./packages/**"  -r build --force` is executed?

nothing to build in the directory ,something like that

**Comment by devhimanshuhc** [comment]
@rrr523 
>No projects matched the filters in "C:\Users\Himanshu Chauhan\OneDrive\Desktop\work\greenfield-js-sdk"

**Comment by devhimanshuhc** [comment]
@rrr523 is there any way to use `yarn` or `npm` instead of `pnpm`? I have never worked with `pnpm`, it is either `npm` or `yarn`.

**Comment by rrr523** [comment]
@devhimanshuhc 

If you only want run example, you can replace package's version in [package.json](https://github.com/bnb-chain/greenfield-js-sdk/blob/main/examples/nodejs/package.json#L8-L9):

```
"@bnb-chain/greenfield-js-sdk": "1.0.6",
"@bnb-chain/greenfiled-file-handle": "1.0.0",
```

Then, you can use `npm` or `yarn` install

**Comment by devhimanshuhc** [comment]
@rrr523 yeah, that worked. thank you!

**Comment by devhimanshuhc** [comment]
@rrr523 i have another issue that everyone is facing including the Support staff in your discord. the issue i am facing is the object is not being uploaded in Dceller, that nodejs example is creating the bucket and the object successfully but in my Dceller dashboard, object in the bucket shows `Upload failed`
![image](https://github.com/bnb-chain/greenfield/assets/80395823/b9406022-55bd-498d-a848-28b0a965a99c)

**Comment by STdevK** [comment]
@devhimanshuhc Can you provide the URL for the failed bucket and object in greenfieldscan? Then we can help confirm the issue.

**Comment by rrr523** [comment]
> @rrr523 i have another issue that everyone is facing including the Support staff in your discord. the issue is the object is not being uploaded in Dceller, that nodejs example is creating the bucket and the object successfully but in my Dceller dashboard, object in the bucket shows `Upload failed` ![image](https://private-user-images.githubusercontent.com/80395823/287040278-b9406022-55bd-498d-a848-28b0a965a99c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDU2MzIsIm5iZiI6MTcwMTQ0NTMzMiwicGF0aCI6Ii84MDM5NTgyMy8yODcwNDAyNzgtYjk0MDYwMjItNTViZC00OThkLWE4NDgtMjhiMGE5NjVhOTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE1NDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOThkZDUwNzc4NTQwZGM1NTdhYzY1MGUxNjk5ZDBhMTE0YzQxN2FhMTQyOGQ4YjJkMjdmMjk2ODcyYzc3MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-lhxiKNcRKvgiLV88gn55uz4YnvYbVoBaZLgQFsaVdc)

@devhimanshuhc  Thank you for reporting the problem 👍 

Our example only supply send tx of create object, not supply upload object.

We had complemented example: https://github.com/bnb-chain/greenfield-js-sdk/blob/main/examples/nodejs/cases/storage.js#L93-L104

**Comment by devhimanshuhc** [comment]
@rrr523 i have been worrying about it since a couple of days, but you must put all the code examples for the new devs who is trying to use Dceller

**Comment by rrr523** [comment]
@devhimanshuhc 

run `storage.js`:

1. create bucket tx
2. create object tx: generate a `txHash`
3. upload object: upload file buffer with `txHash` to ensure file and tx mapping.

Done.

It's how Dcellar operates actually.

**Comment by devhimanshuhc** [comment]
@rrr523 

how can i add multiple objects in a single bucket. well you will find me weird but i have a folder having html css js and i iterated the folder's file to add objects with that `createObject` and `UploadObject` but threw a rpcUrl error. is there a way to put multiple objects all together in a single bucket?

**Comment by CocoStarZ** [comment]
Could you share more details of what you try to achieve and error you got? thx

**Comment by rrr523** [comment]
> @rrr523
> 
> i need to send multiple objects to a particular bucket using `nodejs` implementation.
> 
> I tried to achieve this by looping the files of a folder and uploading it but it didn't work.
> 
> How can I achieve this?

Uploading by folder is not currently supported.

We recommend packaging the resource in html so that it can be easily uploaded.

It just so happens that we have a project like this(Create React App): https://github.com/bnb-chain/greenfield-data-marketplace-frontend/blob/main/package.json#L88

**Comment by devhimanshuhc** [comment]
@rrr523 so mean to say, we cannot put multiple object in one go in a bucket at a time.

plus i didnt understand thi CRA project. can you elaborate it?

**Comment by rrr523** [comment]
@devhimanshuhc 

Greenfield because now does not support folder level upload, that is to say, after a project build such a directory, I am afraid you are difficult to upload with once action:

```
# dist/
| - js
     | - xxx.js
     | - foo.js
| css 
     | - xxx.css
     | - foo.css
| index.html
```

This [project](https://github.com/bnb-chain/greenfield-data-marketplace-frontend/blob/main/package.json#L88) is not important.

We just packaged all the resources in one html file, like:

```
# dist
| - index.html
```

> The downside is that the file may be a little large, but it's easy enough to upload, and there should be CDN support as well, so it's fine.

**Comment by devhimanshuhc** [comment]
@rrr523 

I see. But I did one thing. I am able to upload all the files of a folder in one go(or in one call) if the files are in the root directory.

example
```
./build
---index.html
---styles.css
---app.js
.
.
.
//other files
```

but as you said, you cannot upload the folder structure like subfolders in the root folders, i am working on that logic.

**Comment by KeefeL** [comment]
To upload the `build` folder here, first create an empty object called "build" under your bucket. Then, create the following files one by one: build/index.html, build/styles.css, and build/app.js.

> @rrr523
> 
> I see. But I did one thing. With the logic i have written, I am able to upload all the files of a folder in one go(or in one call) if the files are in the root directory.
> 
> example
> 
> ```
> |---build
>    |---index.html
>    |---styles.css
>    |---app.js
> .
> .
> .
> //other files
> ```
> 
> but as you said, you cannot upload the folder structure like subfolders in the root folders, i am working on that logic.

To upload the `build` folder here, first create an empty object called "build" under your bucket. Then, create the following files one by one: build/index.html, build/styles.css, and build/app.js.

**Comment by CocoStarZ** [comment]
@devhimanshuhc do you still have any issue? we'll close this ticket if not

**Comment by devhimanshuhc** [comment]
> @devhimanshuhc do you still have any issue? we'll close this ticket if not

nope you can close this issue
