### ISSUE TITLE
File upload issue in Greenfield CLI : 

### ISSUE THREAD

**Issue by sudharsansubash2002** [bnb-chain/greenfield#553]
#### System information

Greenfield version: `gnfd-cmd version v1.0.1`
OS & Version: Ubuntu LTS

#### Expected behaviour

Succesful file upload when calling this command:
` gnfd-cmd object put --visibility private ./random_file gnfd://greenfieldtutorial/FirstDemo/randomfile`

#### Actual behaviour

Getting this error : `run command error: fail to load the segment hash`

#### Steps to reproduce the behaviour

Launch a AWS EC2 instance of Ubuntu type (Free tier)
Install Go `go version go1.21.5 linux/amd64`
Install gnfd-cmd `gnfd-cmd v1.0.1` by downloading tar.gz file , extract it .
`cd greenfield-cmd-1.0.1` and `make build`
create config.toml file as mentioned in docs for testnet.
import a metamask account set it as default
create a bucket named greenfieldtutorial and upload file using : `gnfd-cmd object put ./random_file gnfd://greenfieldtutorial/randomfile`

**Comment by deepcrazy** [comment]
Hi there, Could you provide more error logs too? Also, Pls upgrade to v1.0.2 and then try.

Also, follow these steps: https://github.com/bnb-chain/greenfield-cmd?tab=readme-ov-file#installation for installation and these steps: https://github.com/bnb-chain/greenfield-cmd?tab=readme-ov-file#basic-config for setting config file and keystore.
At last, Follow these examples: https://github.com/bnb-chain/greenfield-cmd?tab=readme-ov-file#examples

P.S: I tried this command `./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./sample.txt gnfd://test-dp8-bucket/sample_txt` with v1.0.2 and it worked fine.

**Comment by sudharsansubash2002** [comment]
I have followed the instructions given in provided references to upload file in greenfield as you have mentioned also updated `gnfd-cmd`. 

But still getting same error: 
` ./gnfd-cmd -c ./config.toml object put --contentType "text/xml" --visibility public-read ./filename.txt gnfd://gnfd-bucket-versionnew/gnfd-object
Please enter the passphrase now:
run command error: fail to load the segment hash`

versions used:

- go version go1.21.5 linux/amd64
- Greenfield Cmd Version: v1.0.2

**Comment by deepcrazy** [comment]
Hi there, Can you try out using `go version go1.20.3` instead and see if it works.

- Can you also share the command you used for creating along with it's output?
- It seems like it not able to read the value from keystore? Have you created the keystore in default location (i.e. home location) or created where you have saved .config.toml?
    - Try creating the keystore folder in the same location where you have kept your config.toml by running this command: `./gnfd-cmd --home ./ account import key.txt`
    - And then use `--home ./` flag when uploading the object.

**Comment by sudharsansubash2002** [comment]
Hi, I have installed `go version go1.20.3 linux/amd64` and tried uploading file into greenfield testnet from EC2 instance as you mentioned, but getting this error:

`ubuntu@ip-172-31-38-83:~/greenfield-cmd/build$ ./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./filename.txt gnfd://testbucket/sample_txt`
` Please enter the passphrase now:`
`run command error: fail to load the segment hash`

Following are the commands I have used:
**Install go:**
- wget https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
- tar -xvzf go1.20.3.linux-amd64.tar.gz
- sudo mv go /usr/local/
- set go path.
- source ~/.bashrc
- go version

**Install gnfd-cmd:**
      Followed instrunctions given here : https://github.com/bnb-chain/greenfield-cmd?tab=readme-ov-file#installation

**Upload file:**

- `./gnfd-cmd --home ./ account import key.txt`
- `./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./filename.txt gnfd://testbucket/sample_txt`

**Comment by sudharsansubash2002** [comment]
**Additional info about my project:**
               I am currently working on a project that involves leveraging the **BNB Greenfield testnet** chain for file storage, with the backend implemented in Java Spring Boot. I am reaching out to seek guidance on integrating Greenfield for both file upload and download processes.

Here are my specific queries:

**File Upload APIs:**
                  In the BNB Greenfield documentation (https://greenfield.bnbchain.org/openapi), I found various APIs related to Greenfield. Could you please guide me on which APIs are suitable for uploading files to the BNB Greenfield testnet?. If not, kindly provide relevant APIs I can work with.

**Storage Replacement:**
                   I am exploring the possibility of using the BNB Greenfield testnet as a storage solution to replace IPFS in my project. Could you provide insights into the feasibility of this approach?

**Other Ways:**
                    If no API available Kindly propose other ways I can achieve this.

With this info I believe it will be easier to solve my issue.

 have attached the **Architecture** details and relevant **issues** of my project for your reference.

![My_project_Architecture](https://github.com/bnb-chain/greenfield/assets/104921062/294b25fe-713f-4aa9-aeff-e7849e69a757)
![Issue_Greenfield](https://github.com/bnb-chain/greenfield/assets/104921062/650a658e-58bc-4071-a258-df78374215de)

**Comment by deepcrazy** [comment]
> Hi, I have installed `go version go1.20.3 linux/amd64` and tried uploading file into greenfield testnet from EC2 instance as you mentioned, but getting this error:
> 
> `ubuntu@ip-172-31-38-83:~/greenfield-cmd/build$ ./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./filename.txt gnfd://testbucket/sample_txt` ` Please enter the passphrase now:` `run command error: fail to load the segment hash`
> 
> Following are the commands I have used: **Install go:**
> 
> * wget https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
> * tar -xvzf go1.20.3.linux-amd64.tar.gz
> * sudo mv go /usr/local/
> * set go path.
> * source ~/.bashrc
> * go version
> 
> **Install gnfd-cmd:** Followed instrunctions given here : https://github.com/bnb-chain/greenfield-cmd?tab=readme-ov-file#installation
> 
> **Upload file:**
> 
> * `./gnfd-cmd --home ./ account import key.txt`
> * `./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./filename.txt gnfd://testbucket/sample_txt`
> 
> How can I resolve this issue?

We'll check with the team internally and update here accordingly.

**Comment by KeefeL** [comment]
> **Additional info about my project:** I am currently working on a project that involves leveraging the **BNB Greenfield testnet** chain for file storage, with the backend implemented in Java Spring Boot. I am reaching out to seek guidance on integrating Greenfield for both file upload and download processes.
> 
> Here are my specific queries:
> 
> **File Upload APIs:** In the BNB Greenfield documentation (https://greenfield.bnbchain.org/openapi), I found various APIs related to Greenfield. Could you please guide me on which APIs are suitable for uploading files to the BNB Greenfield testnet?. If not, kindly provide relevant APIs I can work with.
> 
> **Storage Replacement:** I am exploring the possibility of using the BNB Greenfield testnet as a storage solution to replace IPFS in my project. Could you provide insights into the feasibility of this approach?
> 
> **Other Ways:** If no API available Kindly propose other ways I can achieve this.
> 
> With this info I believe it will be easier to solve my issue.
> 
> have attached the **Architecture** details and relevant **issues** of my project for your reference.
> 
> ![My_project_Architecture](https://private-user-images.githubusercontent.com/104921062/294146418-294b25fe-713f-4aa9-aeff-e7849e69a757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTk5NzgsIm5iZiI6MTcwNDQxOTY3OCwicGF0aCI6Ii8xMDQ5MjEwNjIvMjk0MTQ2NDE4LTI5NGIyNWZlLTcxM2YtNGFhOS1hZWZmLWU3ODQ5ZTY5YTc1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwMTU0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWVmZjljMzY4N2RiMWZiNzdmNjM4OWJmZWE0ZTFkODE5ODQ3MGUyNDY5ODAzZmJhYWZlNmIwOTc0ZGRiMTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HImVE0Pq-z9KTqAkNWzKK-uH1XqITImhOI0SPJT35xM) ![Issue_Greenfield](https://private-user-images.githubusercontent.com/104921062/294146462-650a658e-58bc-4071-a258-df78374215de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTk5NzgsIm5iZiI6MTcwNDQxOTY3OCwicGF0aCI6Ii8xMDQ5MjEwNjIvMjk0MTQ2NDYyLTY1MGE2NThlLTU4YmMtNDA3MS1hMjU4LWRmNzgzNzQyMTVkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwMTU0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDc5YjA3YWM2MjAwZGU4Y2Q2ZjE1MjIwNDk5N2EzNDNmNzkyMjg5OGNmYmVmZGU0YmEwZjhmNzRmNmZhYTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ORg_Ry9s4MKgP3vqR46vd049-Kn33R8tWH6giGzwQPU)

Hi @sudharsansubash2002 Here are tutorials on how to store data on Greenfield.
Go tutorial: https://docs.bnbchain.org/greenfield-docs/docs/tutorials/dapp/file-management/overview/
JS tutorial: https://docs.bnbchain.org/greenfield-docs/docs/tutorials/dapp/js-file-management/overview/

It is not recommended to directly use the blockchain API because Greenfield involves Blockchain and SPs. Merely interacting with the blockchain is insufficient. Therefore, I suggest using our SDKs.

**Comment by deepcrazy** [comment]
> Hi, I have installed `go version go1.20.3 linux/amd64` and tried uploading file into greenfield testnet from EC2 instance as you mentioned, but getting this error:
> 
> `ubuntu@ip-172-31-38-83:~/greenfield-cmd/build$ ./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./filename.txt gnfd://testbucket/sample_txt` ` Please enter the passphrase now:` `run command error: fail to load the segment hash`
> 
> Following are the commands I have used: **Install go:**
> 
> * wget https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
> * tar -xvzf go1.20.3.linux-amd64.tar.gz
> * sudo mv go /usr/local/
> * set go path.
> * source ~/.bashrc
> * go version
> 
> **Install gnfd-cmd:** Followed instrunctions given here : https://github.com/bnb-chain/greenfield-cmd?tab=readme-ov-file#installation
> 
> **Upload file:**
> 
> * `./gnfd-cmd --home ./ account import key.txt`
> * `./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./filename.txt gnfd://testbucket/sample_txt`
> 
> How can I resolve this issue?

Hi there, This seems like an issue while calculating the checksum. Can you share the file which you used to upload, so as we can investigate further on it?

**Comment by sudharsansubash2002** [comment]
> > Hi, I have installed `go version go1.20.3 linux/amd64` and tried uploading file into greenfield testnet from EC2 instance as you mentioned, but getting this error:
> > `ubuntu@ip-172-31-38-83:~/greenfield-cmd/build$ ./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./filename.txt gnfd://testbucket/sample_txt` ` Please enter the passphrase now:` `run command error: fail to load the segment hash`
> > Following are the commands I have used: **Install go:**
> > 
> > * wget https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
> > * tar -xvzf go1.20.3.linux-amd64.tar.gz
> > * sudo mv go /usr/local/
> > * set go path.
> > * source ~/.bashrc
> > * go version
> > 
> > **Install gnfd-cmd:** Followed instrunctions given here : https://github.com/bnb-chain/greenfield-cmd?tab=readme-ov-file#installation
> > **Upload file:**
> > 
> > * `./gnfd-cmd --home ./ account import key.txt`
> > * `./gnfd-cmd --config ./config.toml --home ./ object put --visibility public-read ./filename.txt gnfd://testbucket/sample_txt`
> > 
> > How can I resolve this issue?
> 
> Hi there, This seems like an issue while calculating the checksum.
> 
> * Can you share the file which you used to upload, so as we can investigate further on it?
> * Also, please share the bucket name and its transaction details (which was successful).

The file I am trying to upload in greenfield is just a text file I have created for tesing purpose it conttains the following: "Hi this is greenfield testing."
[filename.txt](https://github.com/bnb-chain/greenfield/files/13856281/filename.txt)

**Comment by sudharsansubash2002** [comment]
Hi , I want to create a rest api for my own in nodejs. when i tried uploading file using greenfied js sdk it worked fine but when i tried the same with express.js via self created api  its not working . why? can anyone provide me a reference code are example I can work with. Files are attahed below.
[issue_files.zip](https://github.com/bnb-chain/greenfield/files/13857308/issue_files.zip)

**Comment by deepcrazy** [comment]
> I'm working on creating a REST API in Node.js. Uploading files using the Greenfield JS SDK is successful, but when I attempt the same with Express.js in my custom API, it fails. Any help or reference code/examples would be appreciated.
> 
> I have Attached the files I am working on below.
> 
> [issue_files.zip](https://github.com/bnb-chain/greenfield/files/13857308/issue_files.zip)
> 
> Error: ![image](https://private-user-images.githubusercontent.com/104921062/294869755-684593ae-25d4-419a-a248-6c04058bed31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjcwMzEsIm5iZiI6MTcwNDcyNjczMSwicGF0aCI6Ii8xMDQ5MjEwNjIvMjk0ODY5NzU1LTY4NDU5M2FlLTI1ZDQtNDE5YS1hMjQ4LTZjMDQwNThiZWQzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTEyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDc5YjgwM2EzM2M4Yzc4MDExMzgwMTgxOWM4Y2MyMWJlMWUxNDZjOWE4ZTI2YWU5MzMwYWQ0MGViNGNlNWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LYF8R1B8eGcBUzT41LKcGNckbJN4Y68WETXpFdpW-9s)

From the screenshot shared:
- Seems like your port is already in use as per error in screenshot. 
   - Please change it to another port or kill the already running process on existing port.
- Use `@bnb-chain/greenfiled-file-handle` only for `getCheckSums`. Please refer  https://github.com/bnb-chain/greenfield-js-sdk/blob/9a08e4ac9ca73e8fd1ee2bbd043886ea8095fda4/examples/nodejs/cases/storage.js

PFA of updated and working fileserver.js with package.json.
[Resolved_files.zip](https://github.com/bnb-chain/greenfield/files/13863681/Resolved_files.zip)

P.S: Please refer the package.json file for versions and refer fileserver.js with changes `expectCheckSums` and  `createObjectTx` and some other minor changes.

**Comment by CocoStarZ** [comment]
> **Additional info about my project:** I am currently working on a project that involves leveraging the **BNB Greenfield testnet** chain for file storage, with the backend implemented in Java Spring Boot. I am reaching out to seek guidance on integrating Greenfield for both file upload and download processes.
> 
> Here are my specific queries:
> 
> **File Upload APIs:** In the BNB Greenfield documentation (https://greenfield.bnbchain.org/openapi), I found various APIs related to Greenfield. Could you please guide me on which APIs are suitable for uploading files to the BNB Greenfield testnet?. If not, kindly provide relevant APIs I can work with.
> 
> **Storage Replacement:** I am exploring the possibility of using the BNB Greenfield testnet as a storage solution to replace IPFS in my project. Could you provide insights into the feasibility of this approach?
> 
> **Other Ways:** If no API available Kindly propose other ways I can achieve this.
> 
> With this info I believe it will be easier to solve my issue.
> 
> have attached the **Architecture** details and relevant **issues** of my project for your reference.
> 
> ![My_project_Architecture](https://private-user-images.githubusercontent.com/104921062/294146418-294b25fe-713f-4aa9-aeff-e7849e69a757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTE3NzQsIm5iZiI6MTcwNTg5MTQ3NCwicGF0aCI6Ii8xMDQ5MjEwNjIvMjk0MTQ2NDE4LTI5NGIyNWZlLTcxM2YtNGFhOS1hZWZmLWU3ODQ5ZTY5YTc1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMjQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWI5YjljNGQ0N2UzMTUzYTRjMjkwMWNiZWZjNzc3MmMyMDBiZTY2MTNmNTQxNjI5ZTM3YmMyYWVkNWI4MzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lTzB10KrF1AXET8KaIp67zhAx6Ed3OTQssXgoGLsEKM) ![Issue_Greenfield](https://private-user-images.githubusercontent.com/104921062/294146462-650a658e-58bc-4071-a258-df78374215de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTE3NzQsIm5iZiI6MTcwNTg5MTQ3NCwicGF0aCI6Ii8xMDQ5MjEwNjIvMjk0MTQ2NDYyLTY1MGE2NThlLTU4YmMtNDA3MS1hMjU4LWRmNzgzNzQyMTVkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMjQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDI4Y2FiODM4YjllNGU4OTFhODE5MGMyNDNjMzk4NWVjMzFkMzU2YzAzMzlmOGJjMGU2MjgwMTkwZDk5MzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mijfje5oc1zjVc-SqkjhjT1cJJh5jeptl9Ca6_VLeAA)

For NFT migration you could refer to here: https://docs.bnbchain.org/greenfield-docs/docs/tutorials/dapp/nft-storage/overview/#nft-migration

**Comment by CocoStarZ** [comment]
@sudharsansubash2002  if no other questions, will close this issue. thx

**Comment by sudharsansubash2002** [comment]
Hello everyone, I apologize for the delayed inquiry. This will be my final question, so please be patient with me.

I've used the following code to upload a file, and it has been assigned VISIBILITY_TYPE_PRIVATE:
[greenfieldAPI.txt](https://github.com/bnb-chain/greenfield/files/14079656/greenfieldAPI.txt)

While I want the files to be in private mode, I also need to grant viewing access to specific MetaMask accounts during the file upload to the Greenfield chain. Is there a way to achieve this? 

(i.e) I want to avoid seeing this for specific accounts 

![image](https://github.com/bnb-chain/greenfield/assets/104921062/de15d3d0-7901-4130-84f0-0e822955fab5)

Could you please provide some code as a reference for addressing this issue?

**Comment by sudharsansubash2002** [comment]
> Hello everyone, I apologize for the delayed inquiry. This will be my final question, so please be patient with me.
> 
> I've used the following code to upload a file, and it has been assigned VISIBILITY_TYPE_PRIVATE: [greenfieldAPI.txt](https://github.com/bnb-chain/greenfield/files/14079656/greenfieldAPI.txt)
> 
> While I want the files to be in private mode, I also need to grant viewing access to specific MetaMask accounts during the file upload to the Greenfield chain. Is there a way to achieve this?
> 
> (i.e) I want to avoid seeing this for specific accounts
> 
> ![image](https://private-user-images.githubusercontent.com/104921062/300336441-de15d3d0-7901-4130-84f0-0e822955fab5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzUyNTEsIm5iZiI6MTcwNjc3NDk1MSwicGF0aCI6Ii8xMDQ5MjEwNjIvMzAwMzM2NDQxLWRlMTVkM2QwLTc5MDEtNDEzMC04NGYwLTBlODIyOTU1ZmFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQwODA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGY4ODczMGIxYzVkNDY4ODFhNjE3ZGY2MTBlMGFmMWNkYjExZWE0M2Y3NDIyNjJiNmE1OWE2ZmVmMjg3MWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-GmBKK1Es5DozOKyjqZAOvR5gRLy7AdTl6Pfmpynkeg)
> 
> Could you please provide some code as a reference for addressing this issue?

does anyone here? need help with this

**Comment by CocoStarZ** [comment]
Pls refer to access control to achieve this: https://docs.bnbchain.org/greenfield-docs/docs/tutorials/access-control/

**Comment by sudharsansubash2002** [comment]
Based on your suggestion I have written the following code, 

**need:** I want to update user view permission of a document for a specific metamask account as soon as I upload it, (for upload file kindly scroll above) from backend.

but getting this **error :** 
`Error: Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: Only resource owner can put policy, operator (0x89A1CC91B642DECbC4789474694C606E0E0c420b), owner(0x511d140e09572011b69245C25D47AE22EC8b67b1): Access denied [/go/pkg/mod/cosmossdk.io/errors@v1.0.0-beta.7/errors.go:153] With gas wanted: '18446744073709551615' and gas used: '2400' : unknown request`

**file:** 
[greenfieldAPI2.txt](https://github.com/bnb-chain/greenfield/files/14163756/greenfieldAPI2.txt)

**note:** I am using greenfield-js-sdk so kindly respond with js code. Here ACCOUNT_ADDRESS is the resource owner.

**Comment by sudharsansubash2002** [comment]
My issue has been solved . Thanks for the team"s quick response and community's suppport
